# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.4

# Default target executed when no arguments are given to make.
default_target: all

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/brice/info/c/shake/shake

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/brice/info/c/shake/shake

# Include the progress variables for this target.
include CMakeFiles/progress.make

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake

# Special rule for the target install/local
install/local/fast: install/local

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Only default component available"

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/brice/info/c/shake/shake/CMakeFiles $(CMAKE_ALL_PROGRESS)
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/brice/info/c/shake/shake/CMakeFiles 0

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean

# The main clean target
clean/fast: clean

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1

#=============================================================================
# Target rules for targets named shake

# Build rule for target.
shake: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 shake

# fast build rule for target.
shake/fast:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/build

#=============================================================================
# Target rules for targets named unattr

# Build rule for target.
unattr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unattr

# fast build rule for target.
unattr/fast:
	$(MAKE) -f CMakeFiles/unattr.dir/build.make CMakeFiles/unattr.dir/build

# target to build an object file
executive.o:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/executive.o
	$(MAKE) -f CMakeFiles/unattr.dir/build.make CMakeFiles/unattr.dir/executive.o

# target to preprocess a source file
executive.i:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/executive.i
	$(MAKE) -f CMakeFiles/unattr.dir/build.make CMakeFiles/unattr.dir/executive.i

# target to generate assembly for a file
executive.s:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/executive.s
	$(MAKE) -f CMakeFiles/unattr.dir/build.make CMakeFiles/unattr.dir/executive.s

# target to build an object file
judge.o:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/judge.o

# target to preprocess a source file
judge.i:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/judge.i

# target to generate assembly for a file
judge.s:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/judge.s

# target to build an object file
linux.o:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/linux.o
	$(MAKE) -f CMakeFiles/unattr.dir/build.make CMakeFiles/unattr.dir/linux.o

# target to preprocess a source file
linux.i:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/linux.i
	$(MAKE) -f CMakeFiles/unattr.dir/build.make CMakeFiles/unattr.dir/linux.i

# target to generate assembly for a file
linux.s:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/linux.s
	$(MAKE) -f CMakeFiles/unattr.dir/build.make CMakeFiles/unattr.dir/linux.s

# target to build an object file
main.o:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/main.o

# target to preprocess a source file
main.i:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/main.i

# target to generate assembly for a file
main.s:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/main.s

# target to build an object file
msg.o:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/msg.o

# target to preprocess a source file
msg.i:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/msg.i

# target to generate assembly for a file
msg.s:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/msg.s

# target to build an object file
signals.o:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/signals.o
	$(MAKE) -f CMakeFiles/unattr.dir/build.make CMakeFiles/unattr.dir/signals.o

# target to preprocess a source file
signals.i:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/signals.i
	$(MAKE) -f CMakeFiles/unattr.dir/build.make CMakeFiles/unattr.dir/signals.i

# target to generate assembly for a file
signals.s:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/signals.s
	$(MAKE) -f CMakeFiles/unattr.dir/build.make CMakeFiles/unattr.dir/signals.s

# target to build an object file
unattr.o:
	$(MAKE) -f CMakeFiles/unattr.dir/build.make CMakeFiles/unattr.dir/unattr.o

# target to preprocess a source file
unattr.i:
	$(MAKE) -f CMakeFiles/unattr.dir/build.make CMakeFiles/unattr.dir/unattr.i

# target to generate assembly for a file
unattr.s:
	$(MAKE) -f CMakeFiles/unattr.dir/build.make CMakeFiles/unattr.dir/unattr.s

# Help Target
help::
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... shake"
	@echo "... unattr"
	@echo "... executive.o"
	@echo "... executive.i"
	@echo "... executive.s"
	@echo "... judge.o"
	@echo "... judge.i"
	@echo "... judge.s"
	@echo "... linux.o"
	@echo "... linux.i"
	@echo "... linux.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... msg.o"
	@echo "... msg.i"
	@echo "... msg.s"
	@echo "... signals.o"
	@echo "... signals.i"
	@echo "... signals.s"
	@echo "... unattr.o"
	@echo "... unattr.i"
	@echo "... unattr.s"



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0

